#!/usr/bin/env bash
# AUTHOR: Bram Pulles

readonly OUTPUT_FOLDER="../runs/heat"
mkdir -p "$OUTPUT_FOLDER"

readonly DEFAULTS="-m -v 0 -n 100000 -N 100000 -t 10 -e 0.001 -i 1"
readonly NUM_RUNS=20

readonly runs=(
	#"-S -f major"
	#"-S -f original"
	"-O -f major"
	"-O -f reduction"
	"-O -f schedule"
	"-M -f major -r 1 -R 1"
	"-M -f major -r 2 -R 2"
	"-M -f major -r 3 -R 3"
	"-M -f major -r 4 -R 4"
)

make

for run in ${!runs[*]}
do
	count=$(command ls "$OUTPUT_FOLDER" | wc -l)
	output_file=${OUTPUT_FOLDER}/output$count.csv

	for (( j = 10; j <= 10000000; j = j * 10 ))
	do
		printf "./tester %s\n" "$DEFAULTS ${runs[$run]} -h $j >> $output_file"
		for (( i = 0; i < NUM_RUNS; i++ ))
		do
			./tester $DEFAULTS ${runs[$run]} -h $j >> $output_file
		done
	done
done

make clean

# Do some post processing on the formatting of the files.
cd "$OUTPUT_FOLDER"
sed -i '/^[[:space:]]*$/d' *
for file in $(\ls)
do
	cat "$file" | sort -ur > tmp
	cat tmp > "$file"
done
rm -f tmp
cd - > /dev/null
