#!/usr/bin/env bash
# AUTHOR: Bram Pulles

readonly OUTPUT_FOLDER=output
mkdir -p "$OUTPUT_FOLDER"

readonly DEFAULTS="-m -v 0 -n 1000000 -N 1000000 -t 10 -e 0.01 -h 100.0 -i 1"
readonly NUM_RUNS=20

readonly runs=(
	"-S -f major"
	"-S -f original"
	"-O -f major"
	"-O -f reduction"
	"-O -f schedule"
	"-M -f major -r 1 -R 1"
	"-M -f major -r 2 -R 2"
	"-M -f major -r 3 -R 3"
	"-M -f major -r 4 -R 4"
)

make

for run in ${!runs[*]}
do
	count=$(command ls "$OUTPUT_FOLDER" | wc -l)
	output_file=${OUTPUT_FOLDER}/output$count.csv

    printf "./tester %s\n" "$DEFAULTS ${runs[$run]}"
    printf "./tester %s\n" "$DEFAULTS ${runs[$run]}" > $output_file

	for (( i = 0; i < NUM_RUNS; i++ ))
	do
		./tester $DEFAULTS ${runs[$run]} >> $output_file
	done
done

make clean

# Do some post processing on the formatting of the files.
cd "$OUTPUT_FOLDER"
sed -i '/^[[:space:]]*$/d' *
for file in $(\ls)
do
	cat "$file" | sort -ur > tmp
	cat tmp > "$file"
done
rm -f tmp
cd -
